services:
  user-db:
    platform: linux/arm64/v8
    build:
      context: ./govwifi-user-signup-api/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  user-signup-api:
    platform: linux/arm64/v8
    build:
      context: ./govwifi-user-signup-api
      dockerfile: Dockerfile
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: user-db
      RACK_ENV: development
      S3_SIGNUP_ALLOWLIST_OBJECT_KEY: "somefile"
      S3_SIGNUP_ALLOWLIST_BUCKET: "some_bucket_to_store_signup_allowlist"
      S3_NOTIFICATION_TEMPLATES_BUCKET: "some_bucket_to_store_notification_templates"
      NOTIFY_API_KEY: dummy_key-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000
      GOVNOTIFY_BEARER_TOKEN: "dummy-bearer-token-1234"
      NOTIFY_DO_NOT_REPLY: "do_not_reply_email_template_id"
      NOTIFY_SUPPORT_REPLY: "support_reply_email_template_id"
    links:
      - user-db
    expose:
      - "8080"
    ports:
      - "18080:8080"
    volumes:
      - "./govwifi-user-signup-api:/usr/src/app"
    depends_on:
      user-db:
        condition: service_healthy

  authentication-api:
    platform: linux/arm64/v8
    build:
      context: ./govwifi-authentication-api
      dockerfile: Dockerfile
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: user-db
      RACK_ENV: development
    links:
      - user-db
    expose:
      - "8080"
    ports:
      - "9080:8080"
    depends_on:
      user-db:
        condition: service_healthy
